#pragma once

#define DT_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}
#define DT_VERSION_MINOR ${PROJECT_VERSION_MINOR}
#define DT_VERSION_PATCH ${PROJECT_VERSION_PATCH}
#define DT_VERSION_TWEAK ${PROJECT_VERSION_TWEAK}

#define DT_VERSION_STR "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}.${PROJECT_VERSION_PATCH}.${PROJECT_VERSION_TWEAK}"
